INSERT INTO companies (
  id,
  primary_domain,
  name,
  industry_code,
  industry,
  icon_key,
  country_a2,
  technologies_used,
  city,
  region,
  business_model,
  employee_count,
  business_model_enrichment_attempts,
  business_model_enrich_attempt_at,
  domain_scrape_attempt_at,
  industry_enrich_attempt_at,
  name_enrich_attempt_at,
  icon_enrich_attempt_at,
  scrapin_enrichment_attempts,
  scrapin_enrich_attempt_at,
  country_enrich_attempt_at,
  homepage_scraped,
  domain_scrape_attempts,
  icon_enrichment_attempts,
  industry_enrichment_attempts,
  name_enrichment_attempts,
  country_enrichment_attempts,
  linkedin_ids,
  domains,
  inserted_at,
  updated_at
) VALUES
  ('1', 'acme.com', 'Acme Corporation', 'A1', 'Manufacturing', 'acme-icon', 'US', '{"Elixir","Phoenix"}', 'New York', 'NY', 'B2B', 500, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, false, 0, 0, 0, 0, 0, '{"acme123"}', '{"acme.com"}', NOW(), NOW()),
  ('2', 'globex.com', 'Globex Inc.', 'B2', 'Technology', 'globex-icon', 'GB', '{"React","Node.js"}', 'London', 'London', 'B2C', 1200, 0, NULL, NULL, NULL, NULL, NULL, 0, NULL, NULL, false, 0, 0, 0, 0, 0, '{"globex456"}', '{"globex.com"}', NOW(), NOW()); 