INSERT INTO contacts (
  id,
  first_name,
  last_name,
  full_name,
  linkedin_id,
  linkedin_alias,
  business_email,
  business_email_status,
  personal_email,
  personal_email_status,
  mobile_phone,
  city,
  region,
  country_a2,
  avatar_key,
  job_title,
  company_id,
  seniority,
  department,
  company_domain,
  job_description,
  job_started_at,
  job_ended_at,
  company_started_at,
  location,
  headline,
  summary,
  linkedin_company_id,
  enrich_attempts,
  enrich_attempt_at,
  timezone,
  email_enrich_requested_at,
  phone_enrich_requested_at,
  inserted_at,
  updated_at
) VALUES
  ('contact-1', 'Alice', 'Smith', 'Alice Smith', 'alice-smith-123', 'alice-smith', 'alice.smith@acme.com', 'verified', 'alice.personal@gmail.com', 'unverified', '+1234567890', 'New York', 'NY', 'US', 'alice-avatar', 'CTO', '1', 'executive', 'engineering', 'acme.com', 'Chief Technology Officer at Acme', '2022-01-01 09:00:00', NULL, '2022-01-01 09:00:00', 'New York, NY', 'Leading innovation at Acme', 'Technology leader with 15+ years experience', 'acme123', 0, NULL, 'America/New_York', NULL, NULL, NOW(), NOW()),
  ('contact-2', 'Bob', 'Jones', 'Bob Jones', 'bob-jones-456', 'bob-jones', 'bob.jones@globex.com', 'verified', 'bob.personal@hotmail.com', 'unverified', '+441234567890', 'London', 'London', 'GB', 'bob-avatar', 'Head of Product', '2', 'director', 'product', 'globex.com', 'Head of Product at Globex', '2021-06-15 10:00:00', NULL, '2021-06-15 10:00:00', 'London, UK', 'Building next-gen products', 'Product leader with a passion for user experience', 'globex456', 0, NULL, 'Europe/London', NULL, NULL, NOW(), NOW()); 