import { cva } from 'class-variance-authority';
export const iconVariant = cva('', {
  variants: {
    size: {
      xxs: [],
      xs: [],
      sm: [],
      md: [],
      lg: [],
    },
    variant: {
      solid: [],
      outline: [],
      ghost: [],
    },
    colorScheme: {
      primary: [],
      gray: [],
      success: [],
      error: [],
    },
  },
  compoundVariants: [
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'xxs',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-700'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-700'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-700'],
    },
    {
      size: 'xxs',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-700'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-white'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-600'],
    },
    {
      size: 'xs',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-600'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-4 h-4', 'text-primary-700'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-4 h-4', 'text-gray-700'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-4 h-4', 'text-success-700'],
    },
    {
      size: 'xs',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-4 h-4', 'text-error-700'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-600'],
    },
    {
      size: 'sm',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-600'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-700'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-700'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-700'],
    },
    {
      size: 'sm',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-700'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-white'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-600'],
    },
    {
      size: 'md',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-600'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-5 h-5', 'text-primary-700'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-5 h-5', 'text-gray-700'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-5 h-5', 'text-success-700'],
    },
    {
      size: 'md',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-5 h-5', 'text-error-700'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'solid',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-white'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-primary-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-gray-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-success-600'],
    },
    {
      size: 'lg',
      variant: 'outline',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-error-600'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'primary',
      className: ['w-6 h-6', 'text-primary-700'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'gray',
      className: ['w-6 h-6', 'text-gray-700'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'success',
      className: ['w-6 h-6', 'text-success-700'],
    },
    {
      size: 'lg',
      variant: 'ghost',
      colorScheme: 'error',
      className: ['w-6 h-6', 'text-error-700'],
    },
  ],
});
