name: Core Deploy
on:
  push:
    tags:
      - "v*.*.*"
env:
  APP_NAME: core
  APP_PATH: .
  CONTAINERFILE_PATH: ./Containerfile
  IMAGE_NAME: core
  REGISTRY: ghcr.io
  CGO_ENABLED: 0
  LANG: C.UTF-8
  LC_ALL: C.UTF-8
  CLOUD_REPO: customeros/cloud

permissions:
  contents: write
  pull-requests: read
  packages: write

jobs:
  deploy:
    runs-on: ubicloud-standard-4-arm
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract version from tag
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Sets up an Erlang/OTP environment
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.18.3"
          otp-version: "27.3.4"

      - name: Install Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install Janet from source
        run: |
          wget https://github.com/janet-lang/janet/releases/download/v1.38.0/janet-v1.38.0-linux-x64.tar.gz
          tar -xzf janet-v1.38.0-linux-x64.tar.gz
          cd janet-v1.38.0-linux-x64
          sudo cp janet /usr/local/bin/
          sudo chmod +x /usr/local/bin/janet
          janet -v

      - name: Build Phoenix app
        run: |
          ./scripts/runners/build-core.sh ${{ env.APP_PATH }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOY_TRIGGER_GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push container image
        run: |
          ./scripts/runners/build-and-push-image.sh \
            ${{ env.REGISTRY }} \
            ${{ env.VERSION }} \
            "linux/arm64" \
            "arm64" \
            ${{ env.IMAGE_NAME }} \
            ${{ env.APP_PATH }} \
            ${{ env.CONTAINERFILE_PATH }}

      - name: Checkout cloud repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.CLOUD_REPO }}
          token: ${{ secrets.CLOUD_REPO_KEY }}
          path: cloud
          fetch-depth: 1

      - name: Run deploy script
        run: |
          cd cloud/core
          ./deploy.janet ${{ env.VERSION }}
