name: PR Notifications

on:
  pull_request:
    types: [opened, synchronize, ready_for_review, closed]
  pull_request_review:
    types: [submitted, dismissed]
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest  # You can keep ubicloud if you need to
    if: >
      github.event.pull_request != null && (github.event.pull_request.draft == false || github.event.action == 'ready_for_review')  
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install @actions/core @actions/github node-fetch@3

      - name: Debug context (optional)
        run: echo "${{ toJson(github) }}"

      - name: Run PR Notification Script
        run: node --no-warnings ./scripts/runners/pr-notification.js
        env:
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
