name: PR Notifications

on:
  pull_request:
    types: [opened, synchronize, closed, ready_for_review]
  pull_request_review:
    types: [submitted, dismissed]
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubicloud-standard-2
    if: github.event.pull_request.draft == false || github.event.action == 'ready_for_review'
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm install @actions/core @actions/github node-fetch@3

      - name: Debug Environment
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Current directory: $(pwd)"
          echo "Listing directory contents:"
          ls -la ./scripts/runners/

      - name: Debug GitHub Event
        run: 'echo "${{ toJSON(github.event) }}"'

      - name: Run PR Notification Script
        run: node --input-type=module ./scripts/runners/pr-notification.mjs
        env:
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Script Exit
        if: always()
        run: 'echo "Script exit code: $?"'
