name: PR Notifications

on:
  pull_request:
    types: [opened, synchronize, closed, ready_for_review]
  pull_request_review:
    types: [submitted, dismissed]
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubicloud-standard-2
    if: github.event.pull_request.draft == false || github.event.action == 'ready_for_review'
    steps:
      - uses: actions/checkout@v4

      - name: Slack Notification
        uses: slackapi/slack-github-action@v2.1.0
        with:
          channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
          slack-message: |
            *Pull Request ${{ github.event.action }}*
            *Repository:* ${{ github.repository }}
            *PR Title:* ${{ github.event.pull_request.title }}
            *PR Number:* #${{ github.event.pull_request.number }}
            *Author:* ${{ github.event.pull_request.user.login }}
            *Status:* ${{ github.event.action }}
            *URL:* ${{ github.event.pull_request.html_url }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
